fix: Check version to set correct binary platform suffix name
virtualstaticvoid/asdf-sonarscanner pull request #2
Opened 2024-08-08 09:03 UTC by jesmarla

Due to recent changes in installation script, backwards compatibility with versions older than the latest one has been broken.
![image](https://github.com/user-attachments/assets/e946bf5b-2355-499f-84dd-b4d65020b632)
It is currently not possible to download older versions of the sonar-scanner-cli binary. Backwards compatibility with older versions must be maintained.
This pull request add the changes to check if the version you are trying to install is older than the change in the naming standard imposed by Sonar on its binaries.
If the version is older than the change, it's used the old suffix. If the version is newer, the architecture is added to the platform as is currently done.
![image](https://github.com/user-attachments/assets/6c2b87f5-d751-4190-aca0-86a708c3fb6e)
![image](https://github.com/user-attachments/assets/449971aa-d725-45bc-8417-5dc644696713)
This allow to download any version of the tool.

2024-08-08 11:46 UTC, virtualstaticvoid requested changes
Hi @jesmarla

Thank you for your PR.

I spotted one issue with the change.

Also could you add tests to cover installation of versions before and after the change in download filename convention. Checkout the [`asdf-kubebuilder`](https://github.com/virtualstaticvoid/asdf-kubebuilder/blob/master/.github/workflows/workflow.yml#L29) for an example.

2024-08-08 11:46 UTC, virtualstaticvoid commented on bin/install
> +    if [[ "$version" < "6.1.0.4477" ]]; then
The `version` variable isn't available in the scope of this function. Will need to define an argument to pass it through.

2024-08-08 14:44 UTC, jesmarla commented
I found a new issue.
'<' operator in if statement does not work as I spected.
[[ "4.4.3" < "4.4.4" ]] returns true, but
[[ "4.34.4" < "4.4.4" ]] also returns true, because ASCII comparison detects '3' from '34' is lower than '4'
I've marked the PR as draft until I find a better way to do it.

2024-08-08 15:40 UTC, jesmarla commented
Solved issue found in this comment https://github.com/virtualstaticvoid/asdf-sonarscanner/pull/2#issuecomment-2276009128

2024-08-08 16:08 UTC, virtualstaticvoid approved these changes

2024-08-08 16:09 UTC, virtualstaticvoid commented
Thanks for the updates @jesmarla

I've approved the PR and the tests have run and passed.

Let me know if you are making any further changes, otherwise I will merge.

2024-08-09 05:09 UTC, jesmarla commented
> Thanks for the updates @jesmarla
> 
> I've approved the PR and the tests have run and passed.
> 
> Let me know if you are making any further changes, otherwise I will merge.

It's OK for me now. You can merge this PR when you want.

2024-08-09 05:13 UTC, merged